FROM python:3.11-slim
WORKDIR /workspace
COPY backend/fastapi_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ ./backend/
COPY shared/ ./shared/
COPY data_pipeline/data/ ./data_pipeline/data/
CMD ["uvicorn", "backend.fastapi_app.main:app", "--host", "0.0.0.0", "--port", "8001"]
