FROM python:3.11-slim
WORKDIR /app
COPY backend/django_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/django_app/ .
COPY shared/ ./shared/
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
