FROM python:3.11-slim
WORKDIR /app
COPY data_pipeline/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY data_pipeline/ .
COPY shared/ ./shared/
CMD ["python", "scheduler.py"]
